

// ── Building categories & colors ──────────────────────────────────────────────
export const CATEGORY_COLORS: Record<string, { pin: string; dot: string }> = {
  faculty: { pin: "#1565C0", dot: "#E3F2FD" },
  hostel: { pin: "#6A1B9A", dot: "#F3E5F5" },
  admin: { pin: "#2E7D32", dot: "#E8F5E9" },
  food: { pin: "#2E7D32", dot: "#E8F5E9" },
  library: { pin: "#00838F", dot: "#E0F7FA" },
  medical: { pin: "#C62828", dot: "#FFEBEE" },
  sport: { pin: "#F9A825", dot: "#FFFDE7" },
};

export const NIGHT_MAP_STYLE = [
  { elementType: "geometry", stylers: [{ color: "#242f3e" }] },
  { elementType: "labels.text.fill", stylers: [{ color: "#746855" }] },
  { elementType: "labels.text.stroke", stylers: [{ color: "#242f3e" }] },
  {
    featureType: "road",
    elementType: "geometry",
    stylers: [{ color: "#38414e" }],
  },
  {
    featureType: "road",
    elementType: "geometry.stroke",
    stylers: [{ color: "#212a37" }],
  },
  {
    featureType: "road.highway",
    elementType: "geometry",
    stylers: [{ color: "#746855" }],
  },
  {
    featureType: "water",
    elementType: "geometry",
    stylers: [{ color: "#17263c" }],
  },
];

// ──  UNILAG campus locations ────────────────────────────────────────────────
 
export const BUILDINGS = [
  {
    id: 1,
    name: "Independence Hall",
    latitude: 6.5178,
    longitude: 3.3912,
    icon: "🏠",
    description: "Male hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 2,
    name: "Jaja Hostel",
    latitude: 6.516161, // CORRECTED — big one (was 6.5165, 3.3887) — "King Jaja Hall", 957 reviews
    longitude: 3.3978204,
    icon: "🏠",
    description: "Male hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 3,
    name: "Mariere Hall",
    latitude: 6.519,
    longitude: 3.3906,
    icon: "🏠",
    description: "Male hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 4,
    name: "Moremi Hall",
    latitude: 6.5179703, // CORRECTED (was 6.5182, 3.3894) — verified, 2316 reviews
    longitude: 3.3971292,
    icon: "🏠",
    description: "Female hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 5,
    name: "Queen Idia Hall",
    latitude: 6.5184,
    longitude: 3.3899,
    icon: "🏠",
    description: "Female hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 6,
    name: "Sultan Bello Hall",
    latitude: 6.5176,
    longitude: 3.389,
    icon: "🏠",
    description: "Male hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 7,
    name: "Fabian Olusanya Hall",
    latitude: 6.518,
    longitude: 3.3886,
    icon: "🏠",
    description: "Male hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 8,
    name: "Biobaku Hall",
    latitude: 6.5187,
    longitude: 3.39,
    icon: "🏠",
    description: "Male hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 9,
    name: "Mellanbay Hostel",
    latitude: 6.5174,
    longitude: 3.3884,
    icon: "🏠",
    description: "Female hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 10,
    name: "New Hall",
    latitude: 6.5191717, // CORRECTED (was 6.5192, 3.3909) — verified, 120 reviews
    longitude: 3.3920229,
    icon: "🏠",
    description: "Mixed hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 11,
    name: "Faculty of Arts",
    latitude: 6.517,
    longitude: 3.3918,
    icon: "📚",
    description: "Arts & Humanities — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 12,
    name: "Faculty of Business Admin.",
    latitude: 6.515,
    longitude: 3.3915,
    icon: "💼",
    description: "Business Administration — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 13,
    name: "Faculty of Education",
    latitude: 6.5155,
    longitude: 3.3905,
    icon: "🎓",
    description: "Education — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 14,
    name: "Faculty of Engineering",
    latitude: 6.5181305, // CORRECTED (was 6.5168, 3.394) — verified, 366 reviews
    longitude: 3.3994649,
    icon: "⚙️",
    description: "Engineering & Technology — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 15,
    name: "Faculty of Environmental",
    latitude: 6.5176313, // CORRECTED (was 6.5162, 3.3933) — verified, near main gate
    longitude: 3.3872911,
    icon: "🌿",
    description: "Environmental Sciences — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 16,
    name: "Faculty of Law",
    latitude: 6.5161,
    longitude: 3.3921,
    icon: "⚖️",
    description: "Law & Legal Studies — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 17,
    name: "Faculty of Medicine (CMS)",
    latitude: 6.5145,
    longitude: 3.3925,
    icon: "🩺",
    description: "College of Medicine — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 18,
    name: "Faculty of Pharmacy",
    latitude: 6.5148,
    longitude: 3.393,
    icon: "💊",
    description: "Pharmacy — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 19,
    name: "Faculty of Science",
    latitude: 6.5151215, // CORRECTED (was 6.5176, 3.3931) — verified, 463 reviews
    longitude: 3.3993455,
    icon: "🔬",
    description: "Pure & Applied Sciences — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 20,
    name: "Faculty of Social Sciences",
    latitude: 6.5158892, // CORRECTED slightly (was 6.5158, 3.3917) — verified, 22 reviews
    longitude: 3.391666,
    icon: "📊",
    description: "Social Sciences — Mon–Fri 8am–4pm",
    category: "faculty",
  },
  {
    id: 21,
    name: "Faculty of Dental Sciences",
    latitude: 6.5143,
    longitude: 3.3922,
    icon: "🦷",
    description: "Dental Sciences — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 22,
    name: "Faculty of Nursing",
    latitude: 6.5146,
    longitude: 3.3927,
    icon: "🏨",
    description: "Nursing Sciences — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 23,
    name: "Computer Science Dept.",
    latitude: 6.51515,
    longitude: 3.39999,
    icon: "💻",
    description: "Computer Science — 24hrs",
    category: "faculty",
  },
  {
    id: 24,
    name: "Postgraduate School",
    latitude: 6.5165873, // CORRECTED (was 6.5164, 3.3908) — verified, 277 reviews
    longitude: 3.3864962,
    icon: "🏫",
    description: "Postgraduate studies — Mon–Fri 8am–5pm",
    category: "faculty",
  },
  {
    id: 25,
    name: "Quadrangle",
    latitude: 6.51528,
    longitude: 3.39964,
    icon: "🏛️",
    description: "Central quadrangle — 24hrs",
    category: "faculty",
  },
  {
    id: 26,
    name: "Senate Building",
    latitude: 6.519411, // CORRECTED (was 6.51722, 3.39028) — verified, 432 reviews
    longitude: 3.3989516,
    icon: "🏛️",
    description: "University admin — Mon–Fri 8am–5pm",
    category: "admin",
  },
  {
    id: 27,
    name: "Registry",
    latitude: 6.5173,
    longitude: 3.3901,
    icon: "📋",
    description: "Student records — Mon–Fri 8am–4pm",
    category: "admin",
  },
  {
    id: 28,
    name: "Bursary",
    latitude: 6.5171,
    longitude: 3.39,
    icon: "🏦",
    description: "Finance & Payments — Mon–Fri 8am–3pm",
    category: "admin",
  },
  {
    id: 29,
    name: "ICT Centre",
    latitude: 6.5166,
    longitude: 3.3928,
    icon: "🖥️",
    description: "Tech services — Mon–Sat 8am–8pm",
    category: "admin",
  },
  {
    id: 30,
    name: "Student Union Building",
    latitude: 6.517,
    longitude: 3.391,
    icon: "🎓",
    description: "Student activities — Mon–Fri 9am–5pm",
    category: "admin",
  },
  {
    id: 31,
    name: "America Window on Unilag",
    latitude: 6.51961,
    longitude: 3.39957,
    icon: "🏢",
    description: "Mon–Fri 8am–10pm",
    category: "admin",
  },
  {
    id: 32,
    name: "Vice-Chancellor's Office",
    latitude: 6.5174,
    longitude: 3.3904,
    icon: "🏢",
    description: "VC Office — Mon–Fri 8am–4pm",
    category: "admin",
  },
  {
    id: 33,
    name: "Exams & Records",
    latitude: 6.5172,
    longitude: 3.3906,
    icon: "📝",
    description: "Exam records — Mon–Fri 8am–4pm",
    category: "admin",
  },
  {
    id: 34,
    name: "Alumni Office",
    latitude: 6.5169,
    longitude: 3.3903,
    icon: "🤝",
    description: "Alumni relations — Mon–Fri 9am–4pm",
    category: "admin",
  },
  {
    id: 35,
    name: "SERVICOM Office",
    latitude: 6.5171,
    longitude: 3.3902,
    icon: "📞",
    description: "Service compliance — Mon–Fri 8am–4pm",
    category: "admin",
  },
  {
    id: 36,
    name: "Security Post (Main Gate)",
    latitude: 6.5176848, // verified — matches "UNILAG Gate House" pin closely
    longitude: 3.3854527,
    icon: "🚪",
    description: "Main entrance security — 24 hours",
    category: "admin",
  },
  {
    id: 38,
    name: "UNILAG Back Gate",
    latitude: 6.51395,
    longitude: 3.38795,
    icon: "🔐",
    description: "Main campus entrance — 24 hours",
    category: "admin",
  },
  {
    id: 39,
    name: "Internal Audit Unit",
    latitude: 6.51715,
    longitude: 3.39035,
    icon: "🏢",
    description: "Audit — Mon–Fri 8am–4pm",
    category: "admin",
  },
  {
    id: 40,
    name: "Works & Physical Planning",
    latitude: 6.5168,
    longitude: 3.3896,
    icon: "🏗️",
    description: "Infrastructure — Mon–Fri 8am–4pm",
    category: "admin",
  },
  {
    id: 64,
    name: "UNILAG Chapel",
    latitude: 6.5175,
    longitude: 3.3905,
    icon: "⛪",
    description: "Chapel of Christ Our Light — Sun 7am–12pm",
    category: "admin",
  },
  {
    id: 65,
    name: "UNILAG Mosque",
    latitude: 6.5191731, // CORRECTED (was 6.5177, 3.3907) — "Unilag Islamic Centre", 356 reviews
    longitude: 3.3902119,
    icon: "🕌",
    description: "Central Mosque — Daily prayer times",
    category: "admin",
  },
  {
    id: 66,
    name: "UNILAG Bookshop",
    latitude: 6.5186974, // CORRECTED (was 6.51695, 3.3911) — verified, 1243 reviews
    longitude: 3.397515,
    icon: "📗",
    description: "University Bookshop — Mon–Sat 8am–5pm",
    category: "admin",
  },
  {
    id: 67,
    name: "UNILAG Hotel (Lagoon)",
    latitude: 6.5205,
    longitude: 3.3935,
    icon: "🏨",
    description: "Lagoon Hotel & Conference — 24 hours",
    category: "admin",
  },
  {
    id: 68,
    name: "Car Park (Senate)",
    latitude: 6.51705,
    longitude: 3.39015,
    icon: "🅿️",
    description: "Senate Building car park — 24 hours",
    category: "admin",
  },
  {
    id: 69,
    name: "Tafawa Balewa Square Annex",
    latitude: 6.5164,
    longitude: 3.3937,
    icon: "🏢",
    description: "Annex building — Mon–Fri 8am–5pm",
    category: "admin",
  },
  {
    id: 70,
    name: "UNILAG Pre-Degree Centre",
    latitude: 6.5156,
    longitude: 3.3902,
    icon: "🏫",
    description: "Pre-degree & remedial — Mon–Fri 8am–4pm",
    category: "admin",
  },
  {
    id: 41,
    name: "Amala Joint",
    latitude: 6.5169,
    longitude: 3.3908,
    icon: "🍲",
    description: "Local food — Mon–Sat 7am–9pm",
    category: "food",
  },
  {
    id: 42,
    name: "Dangote Cafeteria",
    latitude: 6.5173,
    longitude: 3.392,
    icon: "🍽️",
    description: "Main cafeteria — Mon–Fri 7am–7pm",
    category: "food",
  },
  {
    id: 43,
    name: "Science Canteen",
    latitude: 6.5177,
    longitude: 3.3935,
    icon: "🥘",
    description: "Canteen — Mon–Sat 7am–8pm",
    category: "food",
  },
  {
    id: 44,
    name: "Engineering Canteen",
    latitude: 6.5165,
    longitude: 3.3942,
    icon: "🍱",
    description: "Canteen — Mon–Fri 7am–6pm",
    category: "food",
  },
  {
    id: 45,
    name: "Moremi Cafeteria",
    latitude: 6.5183,
    longitude: 3.3896,
    icon: "🍽️",
    description: "Hostel cafeteria — Mon–Sat 6am–9pm",
    category: "food",
  },
  {
    id: 46,
    name: "SUB Cafeteria",
    latitude: 6.51695,
    longitude: 3.39095,
    icon: "☕",
    description: "Student Union canteen — Mon–Fri 8am–8pm",
    category: "food",
  },
  {
    id: 47,
    name: "Food Kiosk Area",
    latitude: 6.5165,
    longitude: 3.3913,
    icon: "🥗",
    description: "Street food vendors — Daily 7am–10pm",
    category: "food",
  },
  {
    id: 48,
    name: "Main Library",
    latitude: 6.5200958, // CORRECTED (was 6.5168, 3.3915) — verified pin, 116 reviews
    longitude: 3.3999487,
    icon: "📚",
    description: "Central Library — Mon–Sat 8am–10pm",
    category: "library",
  },
  {
    id: 49,
    name: "Faculty of Law Library",
    latitude: 6.51615,
    longitude: 3.3922,
    icon: "📖",
    description: "Law Library — Mon–Fri 8am–6pm",
    category: "library",
  },
  {
    id: 50,
    name: "Science Library",
    latitude: 6.51755,
    longitude: 3.393,
    icon: "📖",
    description: "Science Library — Mon–Fri 8am–8pm",
    category: "library",
  },
  {
    id: 51,
    name: "Education Library",
    latitude: 6.51545,
    longitude: 3.3906,
    icon: "📖",
    description: "Education Library — Mon–Fri 8am–6pm",
    category: "library",
  },
  {
    id: 52,
    name: "E-Library (ICT Centre)",
    latitude: 6.51665,
    longitude: 3.39275,
    icon: "💾",
    description: "Digital library — Mon–Sat 8am–10pm",
    category: "library",
  },
  {
    id: 53,
    name: "University Health Centre",
    latitude: 6.5141311, // CORRECTED (was 6.516, 3.3905) — verified, "Unilag Medical Centre"
    longitude: 3.3966745,
    icon: "🏥",
    description: "Medical services — 24 hours",
    category: "medical",
  },
  {
    id: 54,
    name: "LASUTH (Teaching Hospital)",
    latitude: 6.5142,
    longitude: 3.3916,
    icon: "🏨",
    description: "Lagos State Teaching Hospital",
    category: "medical",
  },
  {
    id: 55,
    name: "CMS Pharmacy",
    latitude: 6.51475,
    longitude: 3.3929,
    icon: "💊",
    description: "Pharmacy dispensary — Mon–Fri 8am–5pm",
    category: "medical",
  },
  {
    id: 56,
    name: "Dental Clinic",
    latitude: 6.5144,
    longitude: 3.3921,
    icon: "🦷",
    description: "Dental clinic — Mon–Fri 8am–4pm",
    category: "medical",
  },
  {
    id: 57,
    name: "Athletics Track",
    latitude: 6.5188,
    longitude: 3.3925,
    icon: "🏃",
    description: "Athletics track — Daily 5am–8pm",
    category: "sport",
  },
  {
    id: 58,
    name: "Sport Centre",
    latitude: 6.5166212, // CORRECTED (was 6.5185, 3.392) — verified, 3886 reviews
    longitude: 3.3865737,
    icon: "⚽",
    description: "Sports & recreation — 24 hours",
    category: "sport",
  },
  {
    id: 59,
    name: "Swimming Pool",
    latitude: 6.5171424, // CORRECTED (was 6.5186, 3.3923) — verified, 55 reviews
    longitude: 3.3901188,
    icon: "🏊",
    description: "Olympic pool — Mon–Sun 8am–5pm",
    category: "sport",
  },
  {
    id: 60,
    name: "Tennis Court",
    latitude: 6.5187,
    longitude: 3.3918,
    icon: "🎾",
    description: "Tennis courts — Daily 6am–8pm",
    category: "sport",
  },
  {
    id: 61,
    name: "Basketball Court",
    latitude: 6.5184,
    longitude: 3.3916,
    icon: "🏀",
    description: "Basketball courts — Daily 6am–9pm",
    category: "sport",
  },
  {
    id: 62,
    name: "Football Field",
    latitude: 6.519,
    longitude: 3.3922,
    icon: "⚽",
    description: "Main football field — Daily 6am–8pm",
    category: "sport",
  },
  {
    id: 63,
    name: "Multipurpose Hall",
    latitude: 6.5182,
    longitude: 3.3919,
    icon: "🏋️",
    description: "Indoor sports — Mon–Sat 6am–9pm",
    category: "sport",
  },
 
  // ── NEW: added from verified Google Places data ──────────────────────────
  {
    id: 71,
    name: "J.F. Ade Ajayi Auditorium",
    latitude: 6.5192375,
    longitude: 3.3994188,
    icon: "🎭",
    description: "Main Auditorium — Mon–Fri 8am–4pm",
    category: "admin",
  },
  {
    id: 72,
    name: "Faculty of Architecture",
    latitude: 6.5186306,
    longitude: 3.3998855,
    icon: "📐",
    description: "Architecture — Mon–Fri 7am–6pm",
    category: "faculty",
  },
  {
    id: 73,
    name: "UNILAG Indoor Sports Complex",
    latitude: 6.5164975,
    longitude: 3.3881864,
    icon: "🏐",
    description: "Indoor courts (basketball, badminton) — daily",
    category: "sport",
  },
  {
    id: 74,
    name: "Distance Learning Institute (DLI)",
    latitude: 6.5119483,
    longitude: 3.3921009,
    icon: "🎓",
    description: "Distance & part-time learning — Mon–Sat 7:30am–5pm",
    category: "faculty",
  },
  {
    id: 75,
    name: "Unilag Consult",
    latitude: 6.5128297,
    longitude: 3.390790,
    icon: "🏢",
    description: "Consultancy services arm — Mon–Fri 8am–5pm",
    category: "admin",
  },
  {
    id: 76,
    name: "El Kanemi Hall",
    latitude: 6.5160016,
    longitude: 3.3844395,
    icon: "🏠",
    description: "Private hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 77,
    name: "Sodeinde Hostel",
    latitude: 6.519302,
    longitude: 3.3930548,
    icon: "🏠",
    description: "Hostel (New Hall area) — 24 hours",
    category: "hostel",
  },
  {
    id: 78,
    name: "Fagunwa Female Hostel",
    latitude: 6.5199632,
    longitude: 3.3919108,
    icon: "🏠",
    description: "Female hostel (New Hall area) — 24 hours",
    category: "hostel",
  },
  {
    id: 79,
    name: "Henry Carr Postgraduate Hall",
    latitude: 6.5161325,
    longitude: 3.3872541,
    icon: "🏠",
    description: "Postgraduate hall of residence — 24 hours",
    category: "hostel",
  },
  {
    id: 80,
    name: "Testimony Hostels",
    latitude: 6.5172746,
    longitude: 3.383264,
    icon: "🏠",
    description: "Private hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 81,
    name: "ULWS Female Hostel",
    latitude: 6.5107807,
    longitude: 3.393099,
    icon: "🏠",
    description: "Unilag Women Society private female hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 82,
    name: "UNILAG Consult Female Hostel",
    latitude: 6.5225233,
    longitude: 3.3816939,
    icon: "🏠",
    description: "Private female hostel — 24 hours",
    category: "hostel",
  },
  {
    id: 83,
    name: "Salado Cafeteria",
    latitude: 6.5176681,
    longitude: 3.3896141,
    icon: "🍽️",
    description: "Cafeteria & salad bar — Mon–Sat 8am–10pm",
    category: "food",
  },
  {
    id: 84,
    name: "Iya Moria",
    latitude: 6.5117184,
    longitude: 3.3926799,
    icon: "🍲",
    description: "Amala & local dishes — Mon–Sat 10am–10pm",
    category: "food",
  },
  {
    id: 85,
    name: "Korede Spaghetti",
    latitude: 6.5149816,
    longitude: 3.3864743,
    icon: "🍝",
    description: "Spaghetti & rice spot — Daily 12pm–10pm",
    category: "food",
  },
  {
    id: 86,
    name: "Chillspot",
    latitude: 6.5162867,
    longitude: 3.3877647,
    icon: "🥪",
    description: "Shawarma & quick eats — Mon–Sat 9am–9pm",
    category: "food",
  },
 
  // ── NEW (round 2): banks, shops, an extra hostel ──────────────────────────
  // Note: "bank"/"shop" aren't existing categories in your CATEGORY_COLORS /
  // CATEGORY_ICONS / CATEGORIES list — these default to "admin" styling for
  // now. Add a dedicated category later if you want them visually distinct.
  {
    id: 87,
    name: "Wema Bank (UNILAG Branch)",
    latitude: 6.5171425,
    longitude: 3.3868729,
    icon: "🏦",
    description: "Bank branch — Mon–Fri 8am–4pm",
    category: "admin",
  },
  {
    id: 88,
    name: "Unilag Microfinance Bank",
    latitude: 6.5185975,
    longitude: 3.3944026,
    icon: "🏦",
    description: "Bank branch — Mon–Fri 8am–4pm",
    category: "admin",
  },
  {
    id: 89,
    name: "Unilag Pharmacy",
    latitude: 6.5185505,
    longitude: 3.3945179,
    icon: "💊",
    description: "Pharmacy & groceries — Mon–Sat 7am–9pm",
    category: "medical",
  },
  {
    id: 90,
    name: "Yem-Yem Supermarket",
    latitude: 6.5185065,
    longitude: 3.3926534,
    icon: "🛒",
    description: "Supermarket — Mon–Sat 8am–9pm, Sun 12–9pm",
    category: "admin",
  },
  {
    id: 91,
    name: "UNILAG Shopping Complex",
    latitude: 6.5188981,
    longitude: 3.3923655,
    icon: "🏬",
    description: "Shops, salons, business centre — daily 8am–9pm",
    category: "admin",
  },
  {
    id: 92,
    name: "Unilag Water Factory",
    latitude: 6.5193853,
    longitude: 3.3918431,
    icon: "💧",
    description: "Bottled/sachet water plant — Mon–Sat 8am–5pm",
    category: "admin",
  },
  {
    id: 93,
    name: "Madam Tinubu Hall",
    latitude: 6.5203251,
    longitude: 3.3916567,
    icon: "🏠",
    description: "Female hostel (New Hall area) — 24 hours",
    category: "hostel",
  },
  {
    id: 94,
    name: "Unilag Press",
    latitude: 6.5177514,
    longitude: 3.3914689,
    icon: "🖨️",
    description: "University press office — Mon–Fri 8am–4pm",
    category: "admin",
  },
];
export const CAMPUS_BOUNDS = {
  minLat: 6.512,
  maxLat: 6.522,
  minLng: 3.383,
  maxLng: 3.402,
};

